### ISSUE TITLE
help plugin not activate 

### ISSUE THREAD

**Issue by emersonkenji** [rwsite/wc-plugin-update-server#1]
Message

Woocommerce or WPPUS_License_Server is not activated. To work thi plugin, you need to install and activate WooCommerce and WPPUS_License_Server plugins.

**Comment by tikhomirov** [comment]
Yes. This plugin is an integration of [Woocommerce](https://wordpress.org/plugins/woocommerce/) and [WP PUS](https://github.com/froger-me/wp-plugin-update-server). To work with this plugin, you need to install and activate both plugins.

**Comment by emersonkenji** [comment]
so I have the 2 installed but the plugin doesn't work, this message is saying that one of the 2 plugins is missing or woocommerce or wppu the 2 are active but it doesn't work in the same way.

**Comment by tikhomirov** [comment]
I updated the plugin, check it.
