### ISSUE TITLE
Not sure how it works

### ISSUE THREAD

**Issue by yatix100** [rwsite/wc-plugin-update-server#4]
Hello there, first of all this is Amazing integration!

1. WP Plugin update server and Woocommerce installed. 
2. Packaged added on WPPUS with license required
3. New product setup, with required options filed in
4. Placed an order, licence generates, max domain remains empty on order screen
5. MOST IMPORTANT - No license listed on WPPUS License management screen. 

Can you help me out on this please? 

@rwsite

**Comment by yatix100** [comment]
Update: There is not on Order screen "License Key(s) could not be created."

**Comment by yatix100** [comment]
Update: its requires Download limit to function automatically. 
It works now.

**Comment by tikhomirov** [comment]
Hi! It version have some problems. I will try fix them in the future.
For correct work you need set up settings like screens:
1) WP Plugin Update Server https://i.imgur.com/Sk7aIiU.jpeg 
2) Product settings https://i.imgur.com/ujvCiql.jpeg (for lifetime 999, 0 not work), domains 999 for unlimited
3)  The order must be paid https://i.imgur.com/qLd7QCS.jpeg
4) The licence key will be save in the meta-data of wc order https://i.imgur.com/MNAqifD.jpeg 
and in the licenses screen https://i.imgur.com/xSw6KqO.jpeg https://i.imgur.com/rMoPd7q.jpeg

**Comment by gmatta01** [comment]
Hello @rwsite Any chance to for an update? Plugin mostly works. Some fields are not properly passed on to Woocommerce order. 
Also wondering if this will work with Subscription product?
Appreciate your work!
